### PR TITLE
Issue 66

### LINKED ISSUE #66: add bottom bar Menu option to replace settings
Menu will expand options in the bottom bar to include

he asked to redesign the bottom bar of the main win as following: in the position currently occupied by the "Settings" with a "Menu" button. By clicking it, the bottom bar shall open a menu that covers the current widgets and containing the "Settings" button, the "Freeze" button, the "Inspiratory pause" button, the "Expiratory pause", the "Start" buttons, the "Stop" button in red, and finally a button to close the menu. In the position currently occupied by the Start/Stop and Mode Toggle buttons he wants a box with a "Running" label over a green background or a "Stop" label (not button!) with red background according to the current status.

### PR DESCRIPTION
**Pull request by javerom**
Fixes #66 
- reworked GUI main window to accomodate bottom bar overlay
- created new menu widget for additional features
- have status in menu change color when in stopped or running mode

### CODE REVIEW

**Comment by javerom** [comment]
***Note freeze, pause functions are not yet implemented***

**Comment by carmelopellegrino** [comment]
Hi Javier, fantastic work! Thank you! Here are two sub tasks:

- [ ] always show the status green/red box, even when the menu is closed
- [ ] move the Assist/Auto toggle and Stop buttons in the menu

Btw, I'll try to work these out by myself.

**Comment by carmelopellegrino** [comment]
I've updated the PR implementing the above subtasks. I've tested it but I would @javerom approval for merging.

**Comment by javerom** [comment]
I've made a few tweaks to make the text look a bit less cramped. Also I changed the Assist vs Auto button. It now says Mode: Automatic or Mode: Assisted instead of Set Assisted or Set Automatic. In my mind, the simplest thing is to show what the mode is, not what the mode can be changed to by pressing (i.e. when Set Assisted is visible, I have to assume that I'm in Auto mode, which seems like more mental steps). I'm happy to discuss it though :)

**Pull request merged**
