### PR TITLE
Issue 59

### LINKED ISSUE #59: remove the + and - buttons on the bottom widgets of the main window

### PR DESCRIPTION
**Pull request by javerom**
Fixes #59 

- removed +/- from toolsettings
- fixed bug in insp/expr ratio update in settings
- removed extraneous connect update() in toolsettings setup

### CODE REVIEW

**Comment by carmelopellegrino** [comment]
Quick and clean! Thank you! May I also ask you to report the fraction as a fraction? Like if the fraction i `0.5`, the label shows `1:2`. Medical doctors are not used to do math :)

**Comment by javerom** [comment]
Can do this for sure.

**Comment by javerom** [comment]
Hm thinking about this a bit more... We have the ability in the settings window to display numbers from 1 to 3 to produce ratios from 1 to 1:3. However, intermediate values like 2.3 will give fractions as 1:2.3 or 10:23. Clearly we don't want this, so maybe rounding to the nearest fraction (16th) is the way to go?

**Comment by carmelopellegrino** [comment]
What I learned from medical doctors is that they are used to 1:X and 10:Y could confuse them. I think that the easiest thing is to display this as 1:a.b, being a.b a float number with 0.1 precision.

**Comment by carmelopellegrino** [comment]
for example, if I set the denominator to 2.2, I get 7:16 label, which I have to admit is hard to understand also for me :sweat:

**Comment by javerom** [comment]
I think I have it figured out. I'll implement fractions with a maximum denominator, so that they will get values like 1:3 or 1:7 or 1:4 or 2:5. Working on this now

**Comment by carmelopellegrino** [comment]
floating point values are perfectly fine, like `1:2.2`. I think that a float number truncated to the first decimal point is enough. Or I may not understood the problem... Is it because this change have an impact on all other boxes of the same type?

**Comment by javerom** [comment]
Oh I did not realize they were ok with values like 1:2.2 or 1:2.5. That's a much easier problem. I thought they didn't want floating point at all.

**Comment by carmelopellegrino** [comment]
sorry @javerom, it's my fault, I'm having hard time expressing myself correctly :weary:

**Comment by javerom** [comment]
No problem :) I think I've made the necessary changes now.

**Comment by carmelopellegrino** [comment]
Indeed! Great work!

**Pull request merged**
