### PR TITLE
Issue 72. Add a frozen plots window

### PR DESCRIPTION
**Pull request by bs610**
The window is activated when the user clicks "Freeze". It contains frozen waveforms, but live monitors, so the user can still see if something bad is happening.

The monitors on the frozen window are linked to those on the main window - if an alarm is cleared on one, it is cleared on both.

I currently rely on "pinch-to-zoom" for the zooming. If needed, we can add more buttons and scrollbars/arrows to control the zooming. We should test on a real touchscreen while wearing gloves.

The X axes of all 3 plots are linked.

### CODE REVIEW

**Comment by marcodeltutto** [comment]
Hi Ben, thank you for working on this! 
I have a couple of questions/comments:
- I saw that the window that appears is the ~same as the main window, meaning that it still shows the monitors with the current values. This might be misleading as it does not correspond the last value of the frozen plot, and it might appear that the GUI stopped working. I think the idea here was to remove the monitors too, and instead have some more controls on how to zoom in the plots. Maybe we can talk about this at the meeting tomorrow.
- We should try on a real screen, but maybe the pinch-to-zoom will be too hard to use. The idea here was to have the user click on a point in the plot, and then use arrows to zoom in a particular direction, or something similar to this.
- I see you made a new `FreezeDataFiller` class which inherits from `DataFiller`. Are we sure we need it? I think we just ask the DataFiller to get_current_values(), or something like that, to get the current snapshot. If you did it in order to apply the right style easily to the plots, then we should probably separate the styling from `DataFiller` (pack it into a function for example). Apologies if you have other reasons I haven't thought of! I am just worried of inheriting from DataFiller, which is what gets the data from the other thread. If we change things in DataFiller, we will always have to be careful they won't impact the frozen plots.

**Comment by bs610** [comment]
Thanks for the review Marco!

1) Yeah, I was conflicted about what to show, and erred on the side of showing more information rather than less. I would appreciate more thoughts on whether it's best to show live monitors, frozen monitors, or no monitors (to use the space for other things).

2) I went for the 1-line implementation of zooming, but I think you're right that it was a little too optimistic/lazy. We need buttons as well.

3) Yes, I over-complicated things by adding the extra class. I'm sure we can just tweak the main DataFiller class instead.

I'll work on these after the Friday meeting.

**Comment by javerom** [comment]
Hey Ben, thanks for tackling this one! I have a couple comments related to the new UI that is spawned on freeze:

1) Visual: I'll admit that I'm a bit of a stickler for detail, but when the new window pops up, it would be good if the dimensions of the monitors, the plots, and the bottom bar line up so that the user "feels" like its the same window, even though it isn't.

2) Visual: In the newly spawned UI, it would be good if there was some indication still of the mode, similar to what is below the monitors in the main window. This is something that the clinicians seems to like.

3) Implementation: This is related to Marco's comment #3 regarding implementation and is mostly just a suggestion. It seems that there are now two separate kinds of the same window ("mainwindow" and "frozenplots") which must be synced in order to maintain continuity. I am definitely advocate for "if it works, use it", however I wonder if a simpler implementation would be preferable from the perspective of code maintenance. Specifically, instead of spawning a window, freeze could reveal a 3rd layer in the stacked widget "bottombar" that has the "Unfreeze" and "Reset" buttons that you implemented while changing the plot mode in the existing widget (i.e. stop acquiring data and allow plot manipulation). This way, we prevent duplicating the main window and potentially avoid having duplicate our future efforts in maintaining/changing the main window.

Just a few thoughts and I am definitely open to some back-and-forth. Apologies in advance if I've made some assumption about the current implementation that is incorrect :)

**Comment by bs610** [comment]
Thanks for the feedback, Javier. I like the idea of using stackable widgets - it will be much cleaner going forwards.

So, new plan:
* Use stackable widgets
* Use the same plot objects, just change which data is displayed when frozen
* Replace the monitors with Y axis zoom buttons when frozen

**Comment by bs610** [comment]
Thanks all for the comments. This is now a much cleaner implementation using stacked widgets.

I didn't implement "touch to define the centre of zooming" as I got lost in the documentation figuring out how to do it (and I'm concerned about clashing with other mouse logic). So the buttons always zoom based on the centre of the current view.

**Comment by carmelopellegrino** [comment]
Hi Ben, great work! I like it!

Unfortunately there are conflicts which, given my limited knowledge of this big class, I'm not able to resolve quickly. Can you please solve the conflicts?

**Comment by bs610** [comment]
Conflicts between frozen and looping plots resolved in 4d64bfa.

**Comment by marcodeltutto** [comment]
Fantastic, I also tested this, looks good! :D

**Pull request merged**
