### PR TITLE
New startstop ui

### PR DESCRIPTION
**Pull request by javerom**
Streamlined the start_stop_worker and changed the behavior of start/stop auto/assist UI.
Fixed apparent bugs with sending STOP even if not confirmed.

### CODE REVIEW

**Comment by marcodeltutto** [comment]
Hi Javier, I think this looks great. When I click on Start, and then on Stop, the Stop button never turns back to Start. Do you see this behavior too?

**Comment by marcodeltutto** [comment]
Actually, it does, but after some time, and remains grayed out

**Comment by carmelopellegrino** [comment]
I really like how it looks! Though I found two problems:
1. it could be unclear that the "Automatic/Assisted" button is a toggle
2. if I click on "Start Assisted" o "Start Automatic" buttons in the settings window the program crashes with the following exception:
```
Traceback (most recent call last):
  File "/home/carmelo/Work/mvm/gui/gui/settings/settings.py", line 188, in start_worker_auto
    self._start_stop_worker.toggle_automatic()
AttributeError: 'StartStopWorker' object has no attribute 'toggle_automatic'
```
But I'm also thinking whether it is important to have them in the settings window. -> slack!

**Comment by carmelopellegrino** [comment]
I thought about a strategy to cure the crash and I'm going to implement it. I'll first merge this PR and then open a new issue that I'll solve immediately afterwards

**Pull request merged**
